### ISSUE TITLE
i18n: Add language support for zh-hant (Mandarin - Traditional Han script)

### ISSUE THREAD

**Issue by winstonsung** [indoorequal/indoorequal.org#103]
i18n: Add language support for zh-hant (Mandarin - Traditional Han script).

**Comment by francois2metz** [comment]
Hi, the translations are done on Transifex and are community supported: https://www.transifex.com/indoorequal/indoorequalorg/languages/
Once the translation is done, it's integrated on indoor=.

**Comment by winstonsung** [comment]
![Email screenshot](https://github.com/indoorequal/indoorequal.org/assets/52590365/f24012fb-4d9a-445c-9c5a-761b6eace731)

**Comment by francois2metz** [comment]
I clicked on the wrong button yesterday, but I added it manually. Feel free to join the team and start translating.

**Comment by winstonsung** [comment]
Oh, it's added now.
