### ISSUE TITLE
i18n: Remove duplicated zh_TW from Transifex project

### ISSUE THREAD

**Issue by winstonsung** [indoorequal/indoorequal.org#110]
https://app.transifex.com/indoorequal/indoorequalorg/languages/

zh_TW is just a duplicate of zh-Hant in Transifex.

**Comment by francois2metz** [comment]
I guess there is some overlap, but it's still 2 different languages right?

**Comment by winstonsung** [comment]
No. We would only choose either zh-Hant or zh-Hant-TW (zh_TW) for translation as they would and should have identical translations.

The one would be translated separately is zh-Hant-HK (zh_HK).

**Comment by winstonsung** [comment]
https://github.com/wikimedia/translatewiki/blob/79e404d/mw-config/TranslateSettings.php#L214

**Comment by winstonsung** [comment]
Emm... it's still there?

![image](https://github.com/indoorequal/indoorequal.org/assets/52590365/d90767ed-fa91-4830-b888-a4ac06ea8e2a)
