### ISSUE TITLE
Level from URL is not taken into account

### ISSUE THREAD

**Issue by clement-igonet** [indoorequal/indoorequal.org#12]
When level is set in url, it is not applied in the map.

Example:
If I select level 1 in the URL, I'm left in the ground 0.
```
https://indoorequal.org/#map=20.35/48.8603517/2.3525703/-92/59&level=1
```

**Comment by francois2metz** [comment]
It works from me. Which browsers are you using?

**Comment by clement-igonet** [comment]
Sorry, it's seems to be a very local issue... I'm not able to reproduce anymore.

**Comment by francois2metz** [comment]
This one 35c8b389a0b089015e0165ffbc3032ed31771274 I believe

**Comment by clement-igonet** [comment]
OK. I'm lost. Bug is local only. Maybe it comes from my private data...
I close the current issue.
THX.
