### ISSUE TITLE
Purpose of "state" ?

### ISSUE THREAD

**Issue by clement-igonet** [indoorequal/indoorequal.org#13]
Hi.
I set up tilesUrl in config.json like this:
```
(...)
  "tilesUrl": "/data/tmsource____tmp_project.json"
(...)
```
So, when I open the left side bar (menu), this link try to be reached:
`http://localhost:8081/data/tmsource____tmp_project.jsonstate`
Am I wrong ?
Couldn't I set `tilesUrl` as I did ?

And so, even if I fixed this directly in the source code, what is the purpose of `state` ?
In my own server instance (base on tileserver-gl), what should be the response ?

**Comment by francois2metz** [comment]
The state is used to get the date of the latest data update. If you have another tilesUrl, its not working..
