### ISSUE TITLE
Some underground passages are rendered in the map

### ISSUE THREAD

**Issue by pyrog** [indoorequal/indoorequal.org#29]
https://indoorequal.org/#map=18.68/45.7680273/4.8358625&level=-1

This is the tube platform that is rendered as a footway.
i.e. [way 334767499](https://www.openstreetmap.org/way/334767499)

**Comment by francois2metz** [comment]
I don't see anything wrong with the renderer.  The corridor is rendered when selecting the -2 level: https://indoorequal.org/#map=19.2/45.7680552/4.8359585&level=-2
