### ISSUE TITLE
Details of features

### ISSUE THREAD

**Issue by PanierAvide** [indoorequal/indoorequal.org#3]
Hi,
I'm looking forward your indoor rendering, which is very smooth to use and intuitive. It would be great to see more details about shown feature like we do on OpenLevelUp or G**gle Maps :
* Click on a feature on map
* A left panel opens
* It shows main information about clicked element : picture (if any), name, category, website... And maybe tags (by default collapsed)

Some examples

![olu](https://user-images.githubusercontent.com/1349014/76339557-891dd080-62fa-11ea-8f2d-421be40ddff8.png)

![gmaps](https://user-images.githubusercontent.com/1349014/76339711-c08c7d00-62fa-11ea-9999-0f0ad75a1437.png)

Best regards.

**Comment by francois2metz** [comment]
I'm working on it. Here is the current status:

![Screenshot_2020-06-19 indoor=](https://user-images.githubusercontent.com/86659/85171243-eec11780-b26e-11ea-9f61-2e7839030caf.png)

**Comment by PanierAvide** [comment]
Cool, nice to see this feature coming :smile:

**Comment by francois2metz** [comment]
It's live https://indoorequal.org/#map=18.77/48.8408255/2.3204713&level=1&poi=way:703959907

**Comment by PanierAvide** [comment]
![It's beautiful](https://pics.me.me/its-beautiful-ive-looked-at-this-for-five-hours-now-34900664.png)

Just a question, it seems that this description only appear if an icon is there. We have in Rennes our [university mapped indoors](https://indoorequal.org/#map=20.49/48.1184842/-1.703258&level=1) and for some reason no icon or name appear on room (each of them have `indoor=room + room=* + ref=*` at least, often more tags). So we can't have details on them, is it intended ?

**Comment by francois2metz** [comment]
> Just a question, it seems that this description only appear if an icon is there. We have in Rennes our [university mapped indoors](https://indoorequal.org/#map=20.49/48.1184842/-1.703258&level=1) and for some reason no icon or name appear on room (each of them have `indoor=room + room=* + ref=*` at least, often more tags). So we can't have details on them, is it intended ?
Nice work there! I will investigate some rendering difference between OpenLevelUp and indoor=.

About the description, it's only works on POIs (shop/amenity/toursism/exhibit/...). Not sure what I can do on non-poi. 

About the name, indoor= don't support the `ref` tag. My understanding was it not intended to be displayed. Any thoughts?

**Comment by PanierAvide** [comment]
Isn't there any way to get data from polygon features in vector tiles (at least their OSM ID) to retrieve tags from database ?

Good question about `ref=*`. I think that's interesting still to render it as a fallback on rooms only (maybe not all kind of features), as I'm not sure "B303" can be considered as a proper name in OSM.

**Comment by francois2metz** [comment]
> Isn't there any way to get data from polygon features in vector tiles (at least their OSM ID) to retrieve tags from database ?

It's more about what to display to the user. There is only a `ref` and a `room`. And frankly I don't like the `room` tag but I can see the value in non commercial indoor area. 

> Good question about `ref=*`. I think that's interesting still to render it as a fallback on rooms only (maybe not all kind of features), as I'm not sure "B303" can be considered as a proper name in OSM.

Ok, I'll take a look.
