### ISSUE TITLE
New objects are not visible on indoorequal.org

### ISSUE THREAD

**Issue by Michael21011** [indoorequal/indoorequal.org#36]
Hi.
I have added Yesterday several objects according to Simple Indoor Tagging. 

But on https://indoorequal.org its are not shown Today.
Is there any delay till preprocessing and I should wait more time?

**Comment by francois2metz** [comment]
Hi there,

Thanks for your report. 
Updates are done every hour.
Could you give me a link to these objects please ?

**Comment by Michael21011** [comment]
I open it from phone now to get link and it already OK.
https://indoorequal.org/#map=17.61/53.886467/27.427991&level=1
It doesnot show blue mark on small zoom as for others but on big zoom I could see buttons with levels and indoor rooms are shown.

**Comment by francois2metz** [comment]
Hi,

I fixed the bug on the refresh of the heatmap. This should be better now.
