### ISSUE TITLE
Registration issue, confirmation email is absent

### ISSUE THREAD

**Issue by Michael21011** [indoorequal/indoorequal.org#38]
Hi!
I cannot see this email in my mail box.

_**You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you.**_

My original email has only two symbol in name part before @. Could it be reason for issue? I have successfully registered on my another account.

**Comment by francois2metz** [comment]
Hi @Michael21011 

Could you send me an email to contact [at] indoorequal.com with your email so I can take a look at it?

**Comment by Michael21011** [comment]
Hi. Did you fix something or rejected an issue?

**Comment by francois2metz** [comment]
This issue does not belong to this repository. I'll manage that by email ;)
