### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by alenigrelli** [indoorequal/indoorequal.org#39]
Hi! I am mounting the application on a server. the indoorequal server is already ok. but the front end does not show the map. What can be?
![Captura de pantalla de 2021-07-13 10-36-26](https://user-images.githubusercontent.com/15861031/125461427-758368e2-8c93-4cc2-aa63-363cc59626ec.png)

**Comment by francois2metz** [comment]
Hi there,

To know more about the problem, can you tell me if you have done any change to the codebase ? Also could you include a screenshot of the console and the network panel from the web developers tools?

**Comment by alenigrelli** [comment]
do not make any changes to the code. Any other screenshot you need let me know
![Captura de pantalla de 2021-07-13 13-23-15](https://user-images.githubusercontent.com/15861031/125489581-19242348-0d92-4d38-bec1-e6a76aa89889.png)
![Captura de pantalla de 2021-07-13 13-22-19](https://user-images.githubusercontent.com/15861031/125489585-584613fb-d7b3-4cec-9f90-4e3429021b33.png)

**Comment by alenigrelli** [comment]
another image that may be of help
![Captura de pantalla de 2021-07-13 13-32-04](https://user-images.githubusercontent.com/15861031/125490627-4f11aa3a-091b-46a7-bf9b-b7fe59f3440b.png)

**Comment by alenigrelli** [comment]
another image that may be of help
![Captura de pantalla de 2021-07-13 13-33-07](https://user-images.githubusercontent.com/15861031/125490757-fe65a117-b511-4ee0-ba0d-87a6a01354f0.png)

**Comment by francois2metz** [comment]
If you are not using the code on your local host, you need to create your own API key on [maptiler](https://www.maptiler.com/) as well on [indoor=](https://indoorequal.com/) and fill them on the `config.json` file. The currently provided API keys are only working on the dev and production environnement.

**Comment by alenigrelli** [comment]
Thanks for your answer I was able to solve it. now it gives me the following error, I don't know if I make the corresponding configuration.
![Uploading Captura de pantalla de 2021-07-13 18-44-09.png…]()

**Comment by francois2metz** [comment]
You have specified a local host `localhost:8090` but the connection was refused. You should ensure that the server is running.

**Comment by alenigrelli** [comment]
I edit config.json in tilesurl, put the ip of my server, compile the front-end but it still wants to connect to localhost. Is there another configuration so that it does not point to localhost?

**Comment by alenigrelli** [comment]
another question that may be useful your help. Is this giving me this error, has it ever happened to you? Thank you very much and sorry for the inconvenience.
![Captura de pantalla de 2021-07-14 15-43-06](https://user-images.githubusercontent.com/15861031/125675796-33d91b47-dd2e-490a-847a-9cc83fbdc20a.png)

**Comment by francois2metz** [comment]
> I edit config.json in tilesurl, put the ip of my server, compile the front-end but it still wants to connect to localhost. Is there another configuration so that it does not point to localhost?

Rebuilding the application should be enough.To ensure that there is no cache between compilation, you could remove the `.cache` folder.

**Comment by francois2metz** [comment]
> Thanks for your answer I was able to solve it. now it gives me the following error, I don't know if I make the corresponding configuration.
> ![Captura de pantalla de 2021-07-13 18-44-09](https://user-images.githubusercontent.com/15861031/125535920-ed530c5a-5164-4745-a1bc-e1267b35387d.png)

Hard to know without the requests. Could you screenshot the network panel of the developer tools too?

**Comment by alenigrelli** [comment]
> another question that may be useful your help. Is this giving me this error, has it ever happened to you? Thank you very much and sorry for the inconvenience.
> ![Captura de pantalla de 2021-07-14 15-43-06](https://user-images.githubusercontent.com/15861031/125675796-33d91b47-dd2e-490a-847a-9cc83fbdc20a.png)


I managed to solve the connection, but this is the new problem.

**Comment by francois2metz** [comment]
Could you screenshot the network panel of the developer tools too? Or provide me with an access to the instance. Quite difficult to debug without more information.

**Comment by alenigrelli** [comment]
is this information useful?
![Captura de pantalla de 2021-07-15 12-47-37](https://user-images.githubusercontent.com/15861031/125817684-32818cde-d786-4f28-bcdb-088ea7992283.png)

**Comment by francois2metz** [comment]
Could you provide the detail of the request to know more why it failed? Maybe the indoorequal server have some logs too.

**Comment by alenigrelli** [comment]
what I see strange, is that it looks in localhost instead of the ip of my server
![Captura de pantalla de 2021-07-15 15-47-50](https://user-images.githubusercontent.com/15861031/125841314-38f59eff-3ad9-40a1-865b-42564b9da472.png)
![Captura de pantalla de 2021-07-15 15-45-50](https://user-images.githubusercontent.com/15861031/125841328-3fe7307a-9aea-4a10-8f26-5515c6850e7b.png)
![Captura de pantalla de 2021-07-15 15-45-36](https://user-images.githubusercontent.com/15861031/125841331-4631e660-6058-4f78-8f1a-b10e84d483e7.png)

**Comment by alenigrelli** [comment]
when I use this link http: // localhost: 8090 / tiles / 4/5 / 8.pbf? key = sfPRvURZws0DixIXnMlh43 but instead of localhost, I use the ip of my server download me to the corresponding pbf

**Comment by francois2metz** [comment]
Got it. If you are running the indoorequal server on the internet, you have to configure the url of the tiles. 
Run the postserve command with the `--serve` parameter and the base URL of the tiles. For instance, I run the production environnement with `postserve --serve=https://tiles.indoorequal.org indoorequal.yaml`

**Comment by alenigrelli** [comment]
Thanks, it worked perfect !!
