### ISSUE TITLE
indoor=room incorrectly rendered

### ISSUE THREAD

**Issue by Stefal** [indoorequal/indoorequal.org#4]
Hi!

It seems that some rooms are not correctly rendered. See these 4 shops inside Gare de l'Est:
https://indoorequal.org/#map=20.21/48.8766679/2.3600572
![image](https://user-images.githubusercontent.com/8255984/76356781-d0b25580-6316-11ea-95d1-cbe15baae640.png)

(one of these is https://www.openstreetmap.org/way/280670901)

Perhaps it's related to their inner role inside the multipolygon: https://www.openstreetmap.org/relation/9788269

**Comment by francois2metz** [comment]
I believe these shops should have a `level` tag. I'll do it.

**Comment by francois2metz** [comment]
Should be fixed by https://www.openstreetmap.org/changeset/82024364. 

We'll see if these shops are fixed in 40min. 

Anyway thanks for the report!

**Comment by francois2metz** [comment]
Fixed!

![Screenshot_2020-03-10 indoor=(2)](https://user-images.githubusercontent.com/86659/76363591-a4e99c80-6323-11ea-9bad-c1dce95a42c1.png)

**Comment by Stefal** [comment]
Thank you!
