### ISSUE TITLE
Indoormap requires too much zoom on mobile devices

### ISSUE THREAD

**Issue by VladimirMorozov** [indoorequal/indoorequal.org#43]
It isn't possible to get an overview of this shopping centre on a mobile device.
https://indoorequal.org/#map=16.81/59.4219/24.794005&level=0

This is the lowest zoom level at which indoormap appears and as it's clearly seen, the whole building doesn't fit into the viewport. It's not possible to get an overview of the building plan.
![изображение](https://user-images.githubusercontent.com/2279813/150208889-abc786c2-4887-4111-ae4f-8e5bc1552541.png)

**Comment by francois2metz** [comment]
Hi @VladimirMorozov 
Thanks for raising this issue. I'll take a look and see if it make sense to start the indoor rendering at zoom 16.

**Comment by francois2metz** [comment]
Since https://github.com/indoorequal/indoorequal/pull/30 is merged, I'll release a new version of indoor= with the indoor zoom at 16 in the next few weeks.

**Comment by francois2metz** [comment]
Hi @VladimirMorozov. I enabled the indoor zoom at 16. Tell me if it's works for you.

**Comment by VladimirMorozov** [comment]
It works, thank you!
