### ISSUE TITLE
indoor=corridor rendered with wall

### ISSUE THREAD

**Issue by Stefal** [indoorequal/indoorequal.org#5]
Hi!
indoor=corridor are rendered with wall, but the osm wiki says that these objects are "unwalled" (as indoor=area):
![image](https://user-images.githubusercontent.com/8255984/76356272-f5f29400-6315-11ea-8466-941d8bee094a.png)
https://www.openstreetmap.org/way/401291609
https://wiki.openstreetmap.org/wiki/Tag:indoor%3Dcorridor

**Comment by francois2metz** [comment]
Good catch! Fixed in 1da3b1f9880e1a9cbd412b9f7df63b109caf67df.

Before:
![Screenshot_2020-03-10 indoor=](https://user-images.githubusercontent.com/86659/76360742-e4ad8580-631d-11ea-804d-308af55d1792.png)

After:
![Screenshot_2020-03-10 indoor=(1)](https://user-images.githubusercontent.com/86659/76360754-ea0ad000-631d-11ea-8f44-8e1da0c6045c.png)

**Comment by Stefal** [comment]
Yes, that's better!
But, is the thin line between unwalled object really needed?

![image](https://user-images.githubusercontent.com/8255984/76386717-7987a180-6365-11ea-841d-9c80066b155e.png)

**Comment by francois2metz** [comment]
It's complicated. Some area have an exterior wall which is not mapped and the rendering is strange without it. See the examples below.

Before:
![Screenshot_2020-03-11 indoor=(3)](https://user-images.githubusercontent.com/86659/76401878-de9dc000-6382-11ea-9845-683a0327d6c9.png)
After:
![Screenshot_2020-03-11 indoor=(2)](https://user-images.githubusercontent.com/86659/76401886-e198b080-6382-11ea-87a8-620534d44fbe.png)

It also make thinks unusable for the Montrouge Market:
![Screenshot_2020-03-11 indoor=(4)](https://user-images.githubusercontent.com/86659/76401999-1442a900-6383-11ea-9a2e-99c412cdb611.png)

I would love to find something that could improve this.

**Comment by Stefal** [comment]
I understand.
I don't know if something like that is possible because it assumes you manage each multipolygon's "sides" separately:
```
if unwalled_object is in contact with unwalled_object:
    draw_nothing
else
   draw_thin_line
```

BTW : indoor=area for the various shop in the Montrouge Market seems strange as you can't walk on these area.

**Comment by francois2metz** [comment]
> I don't know if something like that is possible because it assumes you manage each multipolygon's "sides" separately:
> 
> ```
> if unwalled_object is in contact with unwalled_object:
>     draw_nothing
> else
>    draw_thin_line
> ```

As far a I know, it's not possible.
 
> BTW : indoor=area for the various shop in the Montrouge Market seems strange as you can't walk on these area.

That's right. Any idea of the tagging scheme to use?

**Comment by Stefal** [comment]
> That's right. Any idea of the tagging scheme to use?

I'm not sure and I didn't found many images of this market.
One solution : 
-mapping the corridor (where the pedestrian can walk)
-removing indoor=area on the shop's polygons

Peut-être qu'on devrait en parler sur la liste talk-fr ou ailleurs.

**Comment by francois2metz** [comment]
I have something in the work on the server side:

![Screenshot_2020-06-24 indoor=(1)](https://user-images.githubusercontent.com/86659/85562715-07de1580-b62d-11ea-81d0-721ad8d31742.png)

**Comment by francois2metz** [comment]
The merge feature issue is now handled in https://github.com/indoorequal/indoorequal/issues/7
