### ISSUE TITLE
Outline for areas with name?

### ISSUE THREAD

**Issue by HMT-HRO-MaMe** [indoorequal/indoorequal.org#53]
Not all special POIs are within a dedicated room, some are only dedicated areas in a building. Examples like fast-food, playground, galleries or places for events have usually a dedicated name or ref.

What do you think about to give this object a soft outline, to indicate their location, but clearly not as prominent like for rooms?
Currently they have no indication and are just "somewhere" within the floor and slightly disappear.
![Screenshot 2022-07-28 at 16-48-58 indoor](https://user-images.githubusercontent.com/102375018/181566863-a7cedec9-4812-4b16-a86b-6b537645070e.png)

For example https://indoorequal.org/#map=19.52/54.0914911/12.1444174&level=0

**Comment by francois2metz** [comment]
The current behavior is to merge unwalled area (area, corridor) unless there is a point of interest. Merging them make a lot of sense most of the time, and naming the area doesn't create walls.
