### ISSUE TITLE
Display room ref 

### ISSUE THREAD

**Issue by HMT-HRO-MaMe** [indoorequal/indoorequal.org#54]
Most rooms / areas that are important have a dedicated name, that is currently rendered fine 😄 
![Screenshot 2022-07-28 at 16-54-04 indoor](https://user-images.githubusercontent.com/102375018/181568698-9aca6caa-623a-43cc-aa3d-8f7642f2bfb9.png)

But of course there are (a lot) of other rooms, that might be relevant for a guest in a school, university, clinic, ... which are just offices or class rooms. Planing your way requires to find the position by the room number / ref  but it is currently not vissible?

I see, that this can be visual overwhelming / clutter , esp. if the rooms have also a icon to present their primary use.
But how about to add a similar text like for name, but even smaller?

Here at OpenLevelUp this isn't that easy to recognize and IMHO a bit like chaos 😉 
![Screenshot 2022-07-28 at 17-02-05 OpenLevelUp!](https://user-images.githubusercontent.com/102375018/181571489-7ff03970-6264-48f5-8d4a-161ec4da9394.png)

**Comment by francois2metz** [comment]
Thanks for reporting this. ref should be supported. There is maybe a regression with latest changes that improve translations. I'll take a look.

**Comment by francois2metz** [comment]
Hi. This will be fixed in the next version / reimport:

- https://github.com/indoorequal/indoorequal/commit/6a29ce311d0c9e21b1a73a6cbe97e04a0d876ca3
 - https://github.com/indoorequal/mapbox-gl-indoorequal/commit/abf1e6638f36c595bf68df44663726f169b53484

Thanks again for reporting this.

**Comment by HMT-HRO-MaMe** [comment]
Hi @francois2metz can you tell me when the next import is scheduled? Looking forward to present it to some other staff of the university 🙂

**Comment by francois2metz** [comment]
Hi, i have a new import almost ready. I will take the time to make it in production probably on Monday.

**Comment by HMT-HRO-MaMe** [comment]
Wow, thats pretty cool, merci! 🥇

**Comment by francois2metz** [comment]
Hi @HMT-HRO-MaMe. The new import is now live!

**Comment by HMT-HRO-MaMe** [comment]
Thank you man! 🎆
