### ISSUE TITLE
Added walls disappear if along border of two floors

### ISSUE THREAD

**Issue by HMT-HRO-MaMe** [indoorequal/indoorequal.org#55]
Hi, I noticed a small bug that might be related to z-order or the floor combination step you mentioned in the other issue.
If you add two floor areas and this areas might be seperated by a wall with a door, currently only the door will be rendered.

For example see:
![Screenshot 2022-08-02 at 08-43-45 indoor](https://user-images.githubusercontent.com/102375018/182310203-c51f82d6-4353-42f7-9536-88b79cfb1b93.png)

But this occurs only in the constellation, where the created wall shares the way with the closed areas. For walls wich just cross a single floor, the rendering is fine
![Screenshot 2022-08-02 at 08-44-12 indoor](https://user-images.githubusercontent.com/102375018/182335140-c50dc512-8a0f-4fea-b3bc-07064ccea43b.png)

**Comment by francois2metz** [comment]
Hi! Thanks for reporting this. 

On the first case, it seems that 2 corridors have been merged, which is fine to me. If there some walls between the 2, you may add a line with `indoor=wall` as they are not supposed to have walls by default. 
For the second case, the areas should have been merged. I need to take a look at it.

**Comment by francois2metz** [comment]
I looked on the data of the second example, and there is wall! It's working as expected for me. Reopen if you find something suspicious again.

**Comment by HMT-HRO-MaMe** [comment]
D'ouh I'm sorry for this issue. I was so sure, that I already added this walls.
Yes, everything working as expected 👍
