### ISSUE TITLE
Rendering some more node POIs?

### ISSUE THREAD

**Issue by HMT-HRO-MaMe** [indoorequal/indoorequal.org#56]
Hi, I would like to suggest, to add some more simple objects which usually appear just as node:
* amenity=lockers
* amenity=table
* amenity=vending_machines
* amenity=photo_booth
* attraction=kiddie_ride 
* amenity=telephone

IMHO this objects are pretty wide spread in buildings like train stations, airports, conference halls and might help to understand the structure of larger areas within the floors?

**Comment by francois2metz** [comment]
`vending_machine`, `photo_booth` and `telephone` nodes are already supported. The others values seems to not be used often.

**Comment by HMT-HRO-MaMe** [comment]
Oh sorry, I missed the vending machines due to the generalization on the most zoom levels.

IMHO lockers are very present at trainstations, gyms, schools, univeristies, ... so where visitors can store their things? 🙂

**Comment by francois2metz** [comment]
A quick followup on this to let you know that I'm in the process to have a special taginfo instance dedicated to indoor features. This will help to prioritize new pois.

**Comment by francois2metz** [comment]
- [`amenity=locker`](https://taginfo.indoorequal.org/tags/amenity=lockers) 64 usage
- [`amenity=table`](https://taginfo.indoorequal.org/tags/amenity=table) 300 usage
- [`attraction=kiddie_ride`](https://taginfo.indoorequal.org/tags/attraction=kiddie_ride) 14 usage

I think the usage is quite low for now. Closing.
