### ISSUE TITLE
Map is not rendered

### ISSUE THREAD

**Issue by mapl** [indoorequal/indoorequal.org#6]
When executing "yarn dev", the map is not rendered.

Inspecting Firefox dev tools reveals the issue: 

**ReferenceError: _typeof is not defined** ce9db94b-da1f-40bc-ba93-41623c29dfcd:5126:7
    Ar blob:http://localhost:1234/ce9db94b-da1f-40bc-ba93-41623c29dfcd:5126
    expression blob:http://localhost:1234/ce9db94b-da1f-40bc-ba93-41623c29dfcd:6930
    Yn blob:http://localhost:1234/ce9db94b-da1f-40bc-ba93-41623c29dfcd:6947
    li blob:http://localhost:1234/ce9db94b-da1f-40bc-ba93-41623c29dfcd:7232
    <anonymous> blob:http://localhost:1234/ce9db94b-da1f-40bc-ba93-41623c29dfcd:9258
    <anonymous> blob:http://localhost:1234/ce9db94b-da1f-40bc-ba93-41623c29dfcd:15032

**My Fix:**
A quick fix has been by adding 

```
"browserslist": [
    "last 2 Chrome versions"
]

```

to the package.json file, the error is gone. 

Mapbox-gl doesn't like to be transpiled by parcel.

**Comment by francois2metz** [comment]
Hi, thanks for the report. 

That's strange, it's already there: https://github.com/indoorequal/indoorequal.org/blob/b64733367acdd81409eb7d846ea3c59ec6ce5838/.babelrc#L5

**Comment by mapl** [comment]
You're right. It seems my parcel version (1.12.4) ignores .babelrc. There some known issues. Will investigate this.

**Comment by francois2metz** [comment]
I upgraded to babel 7 and moved the browserslist config to the package.json file. Could you check that it works?

**Comment by mapl** [comment]
Just cloned the repo again and ran "yarn install" and "yarn run dev".

Works now :)

Thank you!

BTW: would you consider using vue-cli? [https://cli.vuejs.org/](https://cli.vuejs.org/)

**Comment by francois2metz** [comment]
Perfect.

About vue-cli, I prefer not using it. I don't see any benefits to learn this new thing.
