### ISSUE TITLE
OSM attribution not visible iPhone 12 mini

### ISSUE THREAD

**Issue by habi** [indoorequal/indoorequal.org#61]
On an iPhone mini 12 with iOS 16.1 the Attribution-i is out of the viewport.
It can only be seen if one scrolls the viewport with the level-switcher, as seen below.

![IMG_2561](https://user-images.githubusercontent.com/1651235/216924592-42e84d9f-e4a9-45c4-8d82-a7b8963d6ef0.PNG)
![IMG_2562](https://user-images.githubusercontent.com/1651235/216924597-c4b8d125-93f1-4e5a-941f-175d63be6b10.PNG)

**Comment by francois2metz** [comment]
Hi @habi and @LuisAPI, I believe I fixed the bug. Could you confirm?

**Comment by habi** [comment]
You did!
Thanks for the quick fix: 🚀 

![image](https://user-images.githubusercontent.com/1651235/218279791-a0aacfec-03bf-4067-b877-3b9f36e031a2.png)
