### ISSUE TITLE
Problems to render a indoor map using geojson

### ISSUE THREAD

**Issue by ArthurSalomaoo** [indoorequal/indoorequal.org#63]
I have this code but indoor equal does note render the file

```
<body>

</body>
<script>
    const indoorEqualWindow = window.open("https://indoorequal.org/");
window.addEventListener('message', (e) => {
  if (e.data.event === 'ready') {
    const file = new File([JSON.stringify({type: 'FeatureCollection', features: []})], 'mapa.geojson');
    indoorEqualWindow.postMessage({ command: 'preview',file }, '*');
  }
});
</script>
```

This is [mapa.geojson] file(https://gist.github.com/ArthurSalomaoo/54a78604c9edd11d196f70b7c551f223)

Can you help me to make this map visible in indoorequal?

**Comment by francois2metz** [comment]
Hi @ArthurSalomaoo,
The file you are sending on this sample code is empty, without any features. If your geojson features are in the `mapa.geojson` file, you should load/fetch it before sending it to the remote API. You can send an URL and indoorequal will load it.
There a remote tester https://indoorequal.org/remote.html. Try putting the URL of your gist in the "Open preview with URL": https://gist.githubusercontent.com/ArthurSalomaoo/54a78604c9edd11d196f70b7c551f223/raw/7d6c346bdb1b882bfdca66c7dabaa68176caca33/mapa.geojson

**Comment by marmundo** [comment]
HI @francois2metz. I'm his advisor.

On remote tester it works properly. However, using indoor documentation example
`
<script>
    const indoorEqualWindow = window.open("https://indoorequal.org/");
window.addEventListener('message', (e) => {
  if (e.data.event === 'ready') {
    const file = new File([JSON.stringify({type: 'FeatureCollection', features: []})], 'mapa.geojson');
    indoorEqualWindow.postMessage({ command: 'preview',file }, '*');
  }
});
</script>
`
Specifically on `indoorEqualWindow.postMessage({ command: 'preview',file }, '*');` indoor equal doesn't load my geojson.

I've `console.log(file)` object and I can see file content.

What do you suggest to fix this code and load this geojson file using postMessage method?

Thanks.

**Comment by francois2metz** [comment]
> ```
> <body>
>   <input type="file" onchange="showFile(this)">
> 
> </body>
> <script>
>   let arquivo = null
> 
>   let indoorEqualWindow = null
> 
>   function showFile(input) {
> 
>     arquivo = input.files[0];
>     let reader = new FileReader();
> 
>     reader.readAsText(arquivo);
> 
>     reader.onload = function () {
>       arquivoContent = reader.result
>       
>       const arquivo = new File([JSON.stringify(arquivoContent)], 'mapa.geojson');

You declare a new const here that is scoped to the function. You should at least remove the const.

>     };
> 
>     reader.onerror = function () {
>       console.log(reader.error);
>     };
>     indoorEqualWindow = window.open("https://indoorequal.org/");
>   
>   }
> 
>   window.addEventListener('message', (e) => {
> 
>     if (e.data.event === 'ready') {
>     
> 
>       alert('FILE SIZE>>>'+arquivo.size)
>       indoorEqualWindow.postMessage({ command: 'preview', arquivo }, '*');

The second parameter of the preview command must be named `file`, not `arquivo`

>      
>     }
>   });
> ```

I commented a few obvious problems. There is probably a timing issue between the onload of the reader and the listening of the 'ready' event from indoorequal.

**Comment by francois2metz** [comment]
@ArthurSalomaoo Did you make some progress? As this is not an indoor= issue I'm closing this. Feel free to open a discussion that I enabled: https://github.com/orgs/indoorequal/discussions

**Comment by francois2metz** [comment]
Here is a working version: https://jsfiddle.net/2x5m6yuz/

**Comment by marmundo** [comment]
> Here is a working version: https://jsfiddle.net/2x5m6yuz/

Thanks. I’ll open a discuss to discuss with you to evaluate if indoorequal is a viable option to our research project.

**Comment by ArthurSalomaoo** [comment]
Hello, @francois2metz , I would like to ask you a question about using Indoorequal. Could we start a discussion?

**Comment by francois2metz** [comment]
> Hello, @francois2metz , I would like to ask you a question about using Indoorequal. Could we start a discussion?

Sure
