### ISSUE TITLE
Dependency on maptiler

### ISSUE THREAD

**Issue by clement-igonet** [indoorequal/indoorequal.org#8]
Hi, thanks for the job done.

Because of dependency on maptile, I get a cross origin error:
"Origin not allowed - Get your free key at https://cloud.maptiler.com/."

`https://api.maptiler.com/maps/bright/style.json?key=T7HQrA4a6k5eOxDGD6qp`

Must I understand registration on maptiler is mandatory ?

Could you suggest a freer solution ?

**Comment by francois2metz** [comment]
Hi there!

If you are deploying indoor= outside of https://indoorequal.org/, you must use your own api key and edit the filehttps://github.com/indoorequal/indoorequal.org/blob/feab14a95db759830cfdb796339c8d15d2bceb59/config.json 
There is no hard dependency on MapTiler, using another base map provider would be easy.
